### ISSUE TITLE
Simplify d3 chart

### ISSUE THREAD

**Issue by ellvtr** [raiden-network/status-page#11]
## Problem
The code for d3 graphics seem over-complicated. The small d3 chart is spread out on a total of 19 files -- see review here https://github.com/ellvtr/status-page/blob/jonas/misc/angular-app.misc.md#d3-graphics-over-complicated

## Solution
- [ ] Make the d3 chart work on its own without angular, e.g. in dir `/d3viz` -- which is based on the "brainbot design internship" that Paul sent me.
- [ ] Make animation and layout work better than on the current angular page -- like in said design above.
- [ ] Port it in the simplest possible way to angular - or keep it entirely out of angular if deemed useful.

**Comment by ellvtr** [comment]
### From review:

The small d3 chart is spread out on a total of __19 files!__
I suggest a re-write and to simplify that big time. For example, the chart 
can be created without angular; then just include it in the simplest 
possible way, ie as a separate script tag on the `index.html`.

7 files in 3 angular sub components:

```
    src/app/components/visuals/
    ├── graph
    │   ├── graph.component.css
    │   └── graph.component.ts
    └── shared
        ├── index.ts
        ├── link-visual
        │   ├── link-visual.component.css
        │   └── link-visual.component.ts
        └── node-visual
            ├── node-visual.component.css
            └── node-visual.component.ts
```

And 9 files in in `app/src/services/d3`:
(is this even a "service"? IMO angular services provide data, not UI functionality as this does?)

```
    src/app/services/d3/
    ├── d3.service.ts
    ├── directives
    │   ├── draggable.directive.ts
    │   ├── index.ts
    │   └── zoomable.directive.ts
    ├── index.ts
    └── models
        ├── force-directed-graph.ts
        ├── index.ts
        ├── link.ts
        └── node.ts
```

And another 3 files in `src/app/services/graph.visual/`:

```
    src/app/services/graph.visual/
    ├── graph.component.css
    ├── graph.component.html
    └── graph.visual.service.ts
```

**Comment by palango** [comment]
@kelsos Can we merge this with the other issue #18?

**Comment by kelsos** [comment]
@palango I am working on the 3 issues for d3 on the same time so we will close them on a single PR
