### ISSUE TITLE
make responsive UI (ie mobile friendly)

### ISSUE THREAD

**Issue by ellvtr** [raiden-network/status-page#13]
## Problem
It turns out that the current layout is not responsive. We need to re-design layout from scratch using e.g. bootstrap or foundation or similar.

## Solution
- [ ] Rewrite markup and CSS with mobile-first approach
- [ ] Use bootstrap, foundation or similar for the above - and adapt it too look as specified / current layout

**Comment by palango** [comment]
@kelsos You already did some work on the HTML parts. Is this done or does this need more work?

I don't think it's necessary for friday but would be nice for Red Eyes.

**Comment by kelsos** [comment]
@palango I will require some more work to figure out the svg generation part of d3 and make it work nicely on mobile

**Comment by palango** [comment]
> to figure out the svg generation part of d3 and make it work nicely on mobile

It would be nice if it would work, but if it's to much work we can just not show the visualization on mobile.
