### ISSUE TITLE
Decide and create domain

### ISSUE THREAD

**Issue by palango** [raiden-network/status-page#2]
@christianbrb @LefterisJP We need to decide which URL we want the status page to run on. I ropose `status.raiden.network`. Other options are `metrics.raiden.network` or `overview.raiden.network`.

Then Ulo needs to create the subdomain.

**Comment by christianbrb** [comment]
Tools for Lightning are mainly called explorer: https://gist.github.com/bretton/798ec38165ffabc719d91e0f4f67552d

**Comment by palango** [comment]
Explorer is nice as well.

**Comment by franzihei** [comment]
I like explorer.raiden.network or status.raiden.network 
Just to clarify, what will you be able to see / do on that page for the non-tech person amongst us? @palango

**Comment by palango** [comment]
It will display information about the token networks and channels in a user-friendly way as well as encouraging people to try raiden out.

The current mock-up looks like that, feedback is welcome @franzihei 

![raiden-monitor mockup](https://user-images.githubusercontent.com/90851/43824975-c3edac38-9af3-11e8-84fc-b2d187ed81c4.png)

**Comment by franzihei** [comment]
Nice. I would go for **explorer.raiden.network**

**Comment by franzihei** [comment]
Did we also think about visualizations like this 
![image](https://user-images.githubusercontent.com/41991517/43825834-16bd77e8-9af6-11e8-8159-ece647084083.png)

**Comment by christianbrb** [comment]
We should start small and extend it later. Would be even great to find other developers and companies doing it.

**Comment by palango** [comment]
Yes, Jonas is working on visualization as well.

**Comment by palango** [comment]
@ulope We decided on `explorer.raiden.network`. Can you create the subdomain whenever you have a free minute. Thanks!

**Comment by ulope** [comment]
Just discussed this with @palango. I'll create a server and will then also point the domain to it.

One question: The screenshot says 'Testnet'. Should we maybe deploy this twice, both for the testnet and the mainnet?

**Comment by palango** [comment]
> The screenshot says 'Testnet'. Should we maybe deploy this twice, both for the testnet and the mainnet?

Sounds good.
- **explorer.raiden.network** can be the mainnet site
- **ropsten.explorer.raiden.network** can be the testnet site

**Comment by ulope** [comment]
Server and domains are ready.
