### ISSUE TITLE
Make deploy procedure for angular app

### ISSUE THREAD

**Issue by ellvtr** [raiden-network/status-page#20]
## Problem
Currently no production version or docker container for the angular UI app.

## Solution
- [x] Find out how to build angular for production.
- [x] Create docker image / container with production version ready to deploy on server.
- [x] Make it run with `docker-compose`.
- [x] Edit README.

**Comment by ellvtr** [comment]
Relevant resource: https://angular.io/guide/deployment

**Comment by palango** [comment]
@ellvtr Can we us nginx instead of express for serving? It's only static files, right?

**Comment by ellvtr** [comment]
Only static files, yes.

If you decide to use nginx, I suggest we make that a separate issue. The express setup is very simple and runs on a `node:alpine` docker image. To configure nginx is somewhat more complex and requires a different docker setup.

For the KYC solution, express was considered good enough. There was a `traefik` reverse proxy running in front of it, providing SSL encryption.

**Comment by palango** [comment]
> If you decide to use nginx, I suggest we make that a separate issue. The express setup is very simple and runs on a node:alpine docker image. To configure nginx is somewhat more complex and requires a different docker setup.

Fine for me.
