### ISSUE TITLE
adapt webui to suggested new api data schema

### ISSUE THREAD

**Issue by ellvtr** [raiden-network/status-page#29]
## Problem
The current api data is an object `{ }` and parsing it has resulted in some rather complex code that could be greatly simplified by changing the format to an array `[ ]`.
See suggested format here:
https://github.com/ellvtr/status-page/blob/issue12/mock/data/network-info-suggested-format.json
or attached here:
[network-info-suggested-format.json.txt](https://github.com/raiden-network/status-page/files/2318101/network-info-suggested-format.json.txt)

## Solution
- [ ] Make changes to api.
- [ ] Rewrite `net.metrics.service.ts` methods `updateTotalsAndComparativeMetrics`, `restructureAndPersistData` and `setCurrentMetrics` to parse the new format.
   I've already made changes so the rest of the code uses the `currentNetworks` array which is already the new format.

The schema validation shouldn't require changes because the network entries are validated one entry by the time - and they would remain the same in the new format.

**Comment by kelsos** [comment]
@palango I don't think this issue makes sense any more so I am gonna close it.
