### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by palango** [raiden-network/status-page#34]
So, a few things to do here.

When the smart contracts are updated the backend needs some updates:
- [x] Update the contracts version in the [requirements](https://github.com/raiden-network/status-page/blob/master/backend/requirements.txt#L15) 
- [x] Update the TokenNetworkRegistry contract address [here](https://github.com/raiden-network/status-page/blob/master/backend/metrics_backend/metrics_cli.py#L22)
- Otherwise it should just work, the [Dockerfile](https://github.com/raiden-network/status-page/blob/master/backend/Dockerfile) shows how to run it.

Deployment
- Ask @ulope to give you access to the DigitalOcean server
- Setup a deployment `docker-compose` file
  - Add a reverse-proxy, for examples see
     - https://github.com/raiden-network/raiden_token_kyc/blob/master/web/docker-compose.yml
     - https://github.com/ulope/raiden.network-server/blob/master/frontend/etc/containers/raiden.network/docker-compose.yml
    - https://github.com/ulope/raiden.network-server/tree/38d5c2b426171549fb488969ebe843661aab8e31

**Comment by rakanalh** [comment]
Backend deployed here: http://explorer.raiden.network:4567/info

We still need to update the contracts version & addresses but we'll do that once the newer version is released on pypi.

@kelsos FYI

**Comment by palango** [comment]
@kelsos backend is up again: http://explorer.raiden.network:4567/json

**Comment by palango** [comment]
Closing this for more specific issues.
