### ISSUE TITLE
Network graph overlapping footer

### ISSUE THREAD

**Issue by palango** [raiden-network/status-page#44]
The network graph is currently overlapping the footer.
![screen shot 2018-09-20 at 13 52 52](https://user-images.githubusercontent.com/90851/45816655-972dfa80-bcdc-11e8-9c02-32b3e9c76f17.png)

It also sometimes overlaps the header:
![screen shot 2018-09-20 at 14 05 19](https://user-images.githubusercontent.com/90851/45817218-520ac800-bcde-11e8-9b8a-d0350828d598.png)

**Comment by kelsos** [comment]
@palango can you tell me the screen height?

**Comment by palango** [comment]
@kelsos MacBook Air, so 900px total minus some space for firefox UI. Any way I can measure the viewport?

**Comment by kelsos** [comment]
@palango That information is more than enough.
